# Generated by Django 3.2.23 on 2023-11-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('diagnostics', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Records',
            fields=[
                ('Record_id', models.IntegerField()),
                ('Patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Created_date', models.DateField(auto_now_add=True)),
                ('Diagnostics', models.TextField()),
                ('Observations', models.TextField()),
                ('Treatments', models.TextField()),
                ('Department', models.CharField(max_length=100)),
                ('idMisc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
